<a href="https://colab.research.google.com/github/soupriyaaa/ml-lab-assignments/blob/main/06-LR/exp_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target
print ("Iris Dataset Details")
print(f"feature names: {iris.feature_names}")
print(f"target names: {iris.target_names}")
print("\nFirst 5 data samples:")
print(X[:5])

Iris Dataset Details
feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target names: ['setosa' 'versicolor' 'virginica']

First 5 data samples:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
print(f"training set shape: {X_train.shape}")
print(f"testing set shape: {X_test.shape}\n")

training set shape: (120, 4)
testing set shape: (30, 4)



In [ ]:
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

def to_one_hot(labels, num_classes):
  return np.eye(num_classes)[labels]

num_classes = len(np.unique(y_train))
y_train_one_hot = to_one_hot(y_train, num_classes)

print("standardized training data (first 5 samples):")
print(X_train_std[:5])
print("\nOne-hot encoded training labels (first 5 samples):")
print(y_train_one_hot[:5])

standardized training data (first 5 samples):
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

One-hot encoded training labels (first 5 samples):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
class SoftmaxRegression:
  def _intit_self(self, learing_rate=0.1, epochs=1001, l2_lambda=0.01):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.l2_lambda = l2_lambda
    self.weights = None
    self.bias = None
def _softmax(self,z):
  z_shifted = z - np.max(z,axis=1, keepdims=True)
  exp_scores = np.exp(z_shifted)
  return exp_scores / np.sum(exp_scores, axos=1, keepdims = True)

def _cross_entropy_loss(self, y_true_one_hot, y_pred_proba):
  n_samples = y_true_one_hot.shape[0]

